# Generated by Django 5.1.15 on 2026-04-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('parent_transaction', 'installment_number')},
        ),
    ]
