# Generated by Django 5.1.15 on 2026-04-09 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_installment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recurring_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_children', to='transactions.transaction'),
        ),
    ]
