# Generated by Django 5.1.15 on 2026-04-09 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('brand', models.CharField(max_length=50, verbose_name='Bandeira')),
                ('last_four_digits', models.CharField(max_length=4, verbose_name='Últimos 4 dígitos')),
                ('card_type', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], max_length=10, verbose_name='Tipo de cartão')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Limite de crédito')),
                ('billing_close_day', models.IntegerField(blank=True, null=True, verbose_name='Dia de fechamento da fatura')),
                ('billing_due_day', models.IntegerField(blank=True, null=True, verbose_name='Dia de vencimento da fatura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
                'ordering': ['name'],
            },
        ),
    ]
