# Generated by Django 5.1.15 on 2026-04-09 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0003_transaction_recurring_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('input_type', models.CharField(choices=[('texto', 'Texto'), ('audio', 'Áudio')], max_length=10)),
                ('input_content', models.TextField(help_text='Texto digitado pelo usuário ou transcrição do áudio')),
                ('llm_response', models.JSONField(default=dict, help_text='Dados extraídos pela LLM: {name, amount, type, category, date, description, card}')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=15)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_interactions', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interação do Assistente',
                'verbose_name_plural': 'Interações do Assistente',
                'ordering': ['-created_at'],
            },
        ),
    ]
