# Generated by Django 5.1.15 on 2026-04-10 02:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('frequency', models.CharField(choices=[('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal')], max_length=10)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF')], max_length=5)),
                ('filters', models.JSONField(default=dict, help_text='Filtros configurados: {period_start, period_end, category_ids, type, card_ids}')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_send_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório Agendado',
                'verbose_name_plural': 'Relatórios Agendados',
                'ordering': ['next_send_at'],
            },
        ),
    ]
